name: shopsmart_admin_ar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  provider: ^6.0.5
  # Local Memory
  shared_preferences: ^2.1.0
  # Icons
  flutter_iconly: ^1.0.2
  ionicons: ^0.2.2
  # UI
  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.2
  dynamic_height_grid_view: ^0.0.3
  image_picker: ^0.8.7+5
  dotted_border: ^2.0.0+3
  # Utils
  uuid: ^3.0.7
  carousel_slider: ^4.2.1
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  google_sign_in: ^6.1.5
  fluttertoast: ^8.2.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bag/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/profile/
